[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "localhost"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://influxdb_mms1:8086"]
  database = "influx"
  timeout = "5s"
  username = "telegraf"
  password = "metricsmetricsmetricsmetrics"

[[inputs.mqtt_consumer]]
  servers = ["192.168.1.30:1883"]
  qos = 0
  topics = ["qc/mic/demo/#"]
  persistent_session = false
  client_id = ""
  data_format = "json"
  json_string_fields = ["mac_id","spec_id","part_no","rev","process","item_no","item_name","job_id","emp_id","equipment_no"]